# /ghome/wangmr/pysot/scripts/task.pbs             
#PBS -N siamrpn_r50_l234_dwxcorr_otb_8gpu                             
#PBS -o /ghome/wangmr/outputs/siamrpn_r50_l234_dwxcorr_otb_8gpu.out
#PBS -e /ghome/wangmr/outputs/siamrpn_r50_l234_dwxcorr_otb_8gpu.err    
#PBS -l nodes=1:gpus=4:q      
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
echo -n "Node:"
cat $PBS_NODEFILE
echo -n "Gpus:"
cat $PBS_GPUFILE
echo "CUDA_VISIBLE_DEVICES:"$CUDA_VISIBLE_DEVICES
startdocker -D /gpub -u "--ipc=host" -c "sh /ghome/wangmr/pysot/scripts/train.sh" bit:5000/wangmr-pysot-v1

