      
#PBS -N siamrpn_mbv2_l7_dwxcorr_otb_4gpu_1                       
#PBS -o /gdata/wangmr/outputs/pysot/siamrpn_mbv2_l7_dwxcorr_otb_4gpu_1.out
#PBS -e /gdata/wangmr/outputs/pysot/siamrpn_mbv2_l7_dwxcorr_otb_4gpu_1.err    
#PBS -l nodes=1:gpus=4:q
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
echo -n "Node:"
cat $PBS_NODEFILE 
echo -n "Gpus:"
cat $PBS_GPUFILE
echo "CUDA_VISIBLE_DEVICES:"$CUDA_VISIBLE_DEVICES
startdocker -D /gpub -u "-v /gdata/wangmr:/gdata/wangmr --ipc=host" -c "sh /ghome/wangmr/pysot/scripts/train.sh" bit:5000/wangmr-pysot-v1

